/* eslint-disable import/prefer-default-export */
import { Types } from '../../request';
import ApiTag from '../apiTags';
// API doc ref - #12
// -Input
// {}

export const saveDetails = data => {
  const dumy = {
    nriFlag: '',
    cusType: '',
    pageMode: '',
    authToken: '',
    instanceId: '1000000001',
    clientIP: 'null',
    perUPFlag: '',
    cid: 'SHRIKANTH1@GMAIL.COM',
    site: '',
    submitValue: 'Submit',
    countryRes: '77',
    mobileCcode: '',
    fname: 'Shrikanth',
    mname: 'null',
    lname: 'Acharya',
    mobile: '9611874750',
    email: 'NITTE9@GMAIL.COM',
    custId: '',
    secnumber: '765432189',
    sinNumber: '',
    NriAccReqFlag: 'false',
    address1: 'test',
    address2: 'test',
    city: 'Cordova',
    state: 'Alaska',
    zipCode: '13344',
    promoCode: '',
    declareTerms: '',
    phoneCcode: '1',
    phoneCityCode: '123457',
    phoneno: '9611874750',
    valueDate: '',
    about: '',
    inputField: '',
    password: 'KR5majS1zwBvJvl1',
    hquestion: '',
    hansw: '',
    simpleCaptcha: '',
    imgans: '',
    aincome: '',
    qualification: '',
    perOfStay: '',
    occupation: '',
    accountStatus: '',
    pmail: '',
    login: '',
    passwordJumio: '',
    nationality: '77',
    mktflag: '',
    legalstatus: 'Corporation',
    doingbusiness: 'IT',
    authaddress1: 'test',
    authaddress2: 'test',
    authcity: 'Seattle',
    authstatus: 'Washington',
    authZipCode: '13344',
    workphoneno: '23356789018',
    getPath: '',
    lnStatusForZeroLimit: '',
    sessionId: data,
    perToStay: '',
    rssn: '765432189',
    rsin: '',
    dd: '28',
    mm: '11',
    yyyy: '1991',
    gender: 'M',
    goToStep: 'goToStep3',
    agreeTerms: 'on',
    fullname: 'IT company',
    tineinno: '120985361',
    authdob: '21/08/1993',
    beneficialOwners: 'N',
    password2: 'KR5majS1zwBvJvl1',
    ribProcessFlag: '',
    ribsrno: '',
    sitecode: 'USweb-login',
    utmSource: 'null',
    utmMedium: 'null',
    utmCampaign: 'null',
    utmAdgroup: 'null',
    utmTerm: 'null',
    utmContent: 'null',
    txtdob: '24/11/2010',
    userType: 'BUSINESS',
    marktMailFlg: '',
    nriEvent: 'yes',
    nriAccNum: 'null',
    remoteAddr: '',
    cpncode12: '',
  };

  return {
    url: '/signup/registerAboutDetails',
    payload: data,
    type: Types.POST,
    tag: ApiTag.SAVE_DETAILS,
    headers: {},
  };
};
